Update connection.js
connectRedis throws an exception.

ReplyError: NOAUTH Authentication required.

The redis password should be supplied in a password property.

See 
Line 71 of https://github.com/luin/ioredis/blob/v4.28.5/lib/redis/RedisOptions.ts